name: mqtt5_client
description: A server and browser based MQTT5 client for Dart supporting normal, secure sockets and websockets.
version: 3.4.0
repository: https://github.com/shamblett/mqtt5_client
homepage: https://github.com/shamblett/mqtt5_client

environment:
 sdk: '>=2.17.0 <3.0.0'

funding:
 - https://www.darticulate.com/#funding

dependencies:
 typed_data: '^1.3.1'
 event_bus: '^2.0.0'
 path: '^1.8.2'
 crypto: '^3.0.2'
 meta: '^1.8.0'
 
dev_dependencies:
 test: '^1.23.1'
 mockito: '^5.3.2'
 build_runner: '^2.3.3'
 build_test: '^2.1.6'
 build_web_compilers: '^3.2.7'
 lints: '^2.0.1'

false_secrets:
  - /test/pem/self_signed.key
  - /test/pem/localhost.key




