name: mqtt5_client
description: A server and browser based MQTT5 client for Dart supporting normal, secure sockets and websockets.
version: 4.14.0
repository: https://github.com/shamblett/mqtt5_client
homepage: https://github.com/shamblett/mqtt5_client

environment:
 sdk: '>=3.8.0 <4.0.0'

funding:
 - https://www.darticulate.com/#funding

dependencies:
 typed_data: '^1.4.0'
 event_bus: '^2.0.1'
 path: '^1.9.0'
 universal_html: '^2.2.4'
 crypto: '^3.0.6'
 meta: '^1.15.0'
 web: '>=0.5.0 <2.0.0'
 characters: '^1.4.0'
 
dev_dependencies:
 test: '^1.25.8'
 mockito: '^5.4.4'
 mocktail: '^1.0.4'
 build_runner: '^2.4.13'
 build_test: '^2.2.2'
 build_web_compilers: '^4.0.11'
 lints: '^5.0.0'
 dart_code_metrics_presets: '^2.21.0'
 aws_common: '^0.7.6'
 aws_signature_v4: '^0.6.5'
 http: '^1.4.0'

topics:
  - iot
  - chat
  - mqtt
  - data

screenshots:
    - description: 'MQTT Specification'
      path: example/screenshots/mqtt-ver.webp
    - description: 'MQTT IOT Usage'
      path: example/screenshots/MQTT-1.webp
      
false_secrets:
  - /test/pem/self_signed.key
  - /test/pem/localhost.key




