name: mqtt5_client
description: A server and browser based MQTT5 client for Dart supporting normal, secure sockets and websockets.
version: 4.1.0
repository: https://github.com/shamblett/mqtt5_client
homepage: https://github.com/shamblett/mqtt5_client

environment:
 sdk: '>=3.0.0 <4.0.0'

funding:
 - https://www.darticulate.com/#funding

dependencies:
 typed_data: '^1.3.2'
 event_bus: '^2.0.0'
 path: '^1.8.2'
 crypto: '^3.0.3'
 meta: '^1.9.1'
 
dev_dependencies:
 test: '^1.25.0'
 mockito: '^5.4.4'
 build_runner: '^2.4.7'
 build_test: '^2.2.2'
 build_web_compilers: '^4.0.7'
 lints: '^3.0.0'

false_secrets:
  - /test/pem/self_signed.key
  - /test/pem/localhost.key




