name: mqtt5_client
description: A server and browser based MQTT5 client for Dart supporting normal, secure sockets and websockets.
version: 3.1.1
homepage: https://github.com/shamblett/mqtt5_client

environment:
 sdk: '>=2.12.0 <3.0.0'

dependencies:
 typed_data: '^1.3.0'
 event_bus: '^2.0.0'
 path: '^1.6.4'
 crypto: '^3.0.0'
 meta: '^1.3.0'

dev_dependencies:
 test: '^1.16.8'
 mockito: '^5.0.3'
 pedantic: '^1.9.0'
 build_runner: '^1.12.2'
 build_test: '^2.0.0'
 build_web_compilers: '^2.16.3'





