name: mqtt5_client
description: A server and browser based MQTT5 client for Dart supporting normal, secure sockets and websockets.
version: 3.3.2
homepage: https://github.com/shamblett/mqtt5_client

environment:
 sdk: '>=2.17.0 <3.0.0'

funding:
 - https://www.darticulate.com/#funding

dependencies:
 typed_data: '^1.3.0'
 event_bus: '^2.0.0'
 path: '^1.6.4'
 crypto: '^3.0.0'
 meta: '^1.3.0'

dev_dependencies:
 test: '^1.21.1'
 mockito: '^5.2.0'
 build_runner: '^2.1.11'
 build_test: '^2.1.5'
 build_web_compilers: '^3.2.3'
 lints: '^2.0.0'

false_secrets:
  - /test/pem/self_signed.key
  - /test/pem/localhost.key




